program: score_matching_model.ipynb
method: random
metric:
  name: test_loss
  goal: minimize
parameters:
  lr:
    min: 0.0001
    max: 0.01
    distribution: log_uniform
  epochs:
    values: [100, 200, 300, 400, 500]
  batch_size:
    values: [32, 64, 128, 256, 512]
  num_steps:
    values: [10, 20, 30, 40, 50]
  rel_emb_dim:
    values: [50, 100, 150, 200]
  similarity_metric:
    values: ['cosine', 'l2']
  k:
    value: 10
