program: embedding_model.ipynb
method: random
metric:
  name: val_loss
  goal: minimize
parameters:
  dataset_name:
    values: ["FB15k_237", "Planetoid", "AmazonProducts"]
  model_name:
    values: ["RotatE", "TransE", "ComplEx", "DistMult"]
  epochs:
    values: [100, 1000]
  batch_size:
    values: [500, 1000, 1500, 2000, 2500]
  lr:
    min: 0.0001
    max: 0.01
    distribution: log_uniform_values
  weight_decay:
    values: [1e-7, 1e-6, 1e-5, 1e-4]
  k:
    value: 10
  hidden_channels:
    values: [32, 64, 128, 256, 512]
  verbose:
    value: False
