program: embedding_model.ipynb
method: random
metric:
  name: val_loss
  goal: minimize
parameters:
  hidden_channels:
    values: [25, 50, 75, 100, 125,150,175, 200, 225, 250]
  epochs:
    values: [500, 750, 1000, 1250, 1500, 2000, 2250, 2500]
  batch_size:
    values: [500, 1000, 1500, 2000, 2500]
  lr:
    min: 0.0001
    max: 0.01
    distribution: log_uniform
  weight_decay:
    values: [1e-7, 1e-6, 1e-5, 1e-4]
  k:
    value: 10
