program: embedding_model.ipynb
method: bayes
metric:
  name: val_relation_mean_rank
  goal: minimize
parameters:
  dataset_name:
    values: ["FB15k_237"]
  embedding_model_name:
    values: ["ComplEx"]
  task:
    values: ["kg_completion"]
  max_epochs:
    values: [2500]
  batch_size:
    values: [512]
  lr:
    min: 0.001
    max: 0.1
    distribution: log_uniform_values
  weight_decay:
    values: [1e-7, 1e-6, 1e-5]
  k:
    value: [1, 3, 10]
  hidden_channels:
    values: [64, 128, 512, 1024]
  verbose:
    value: False
  num_epochs_without_improvement_until_early_finish:
    value: 5
  validate_after_this_many_epochs:
    value: 10
