program: embedding_model.ipynb
method: bayes
metric:
  name: val_relation_mean_rank
  goal: minimize
parameters:
  dataset_name:
    values: ["FB15k_237", "WordNet18RR", "WordNet18"]
  embedding_model_name:
    values: ["DistMult"]
  task:
    values: ["kg_completion"]
  max_epochs:
    values: [2500]
  batch_size:
    values: [512]
  lr:
    min: 0.00015
    max: 0.015
    distribution: log_uniform_values
  weight_decay:
    values: [1e-7, 1e-6, 1e-5]
  k:
    value: [1, 3, 10]
  hidden_channels:
    values: [64, 128, 512, 1024]
  margin:
    value: 0.5
  verbose:
    value: False
  num_epochs_without_improvement_until_early_finish:
    value: 3
  validate_after_this_many_epochs:
    value: 10
