wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710686511.950605
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 1
      - 2
      - 3
      - 13
      - 23
      - 37
      4: 3.9.18
      5: 0.16.3
      8:
      - 1
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 500
epochs:
  desc: null
  value: 1000
hidden_channels:
  desc: null
  value: 225
k:
  desc: null
  value: 10
lr:
  desc: null
  value: 1.0082876191581576
weight_decay:
  desc: null
  value: 0.0001
